framework:
    default_locale: '%env(APP_LOCALE)%'
    translator:
        default_path: '%kernel.project_dir%/assets/translations'
        fallbacks:
            - '%env(APP_FALLBACK_LOCALE)%'
        
#        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
#            phrase:
#                dsn: '%env(PHRASE_DSN)%'
